version: '3'

services:
  python:
    build: ./docker/python
  #   ports:
  #     - "5000:5000"
    volumes:
      - "./src:/var/www"
    tty: true
    environment:
      TZ: Asia/Tokyo

  # nginx:
  #   image: nginx
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./src:/var/www
  #     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - python

  https-portal:
    image: steveltn/https-portal
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DOMAINS: "hisafi.com, shamemo.com -> http://python:5000"
      STAGE: "production"
      # FORCE_RENEW: 'true'
      # DOMAINS: "localhost -> http://python:5000"
      # STAGE: "local"
    volumes:
      - ./docker/https-portal:/var/lib/https-portal
      - /var/www/html:/var/www/vhosts

  db:
    image: mariadb
  #  ports:
  #    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/conf:/etc/mysql/conf.d
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.