version: '3'

services:
  app:
    container_name: php53
    build: ./docker/app
    ports:
    - 8080:80
    volumes:
    - ./src:/var/www/html

  # nginx:
  #   image: nginx
  #   container_name: nginx
  #   ports:
  #   - 8080:80
  #   volumes:
  #   - ./src:/var/www
  #   - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #   - php

  # db:
  #   image: mysql:5.7
  #   container_name: db-host
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: database
  #     MYSQL_USER: docker
  #     MYSQL_PASSWORD: docker
  #     TZ: 'Asia/Tokyo'
  #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   volumes:
  #   - ./docker/db/data:/var/lib/mysql
  #   - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  #   - ./docker/db/sql:/docker-entrypoint-initdb.d
  #   ports:
  #   - 3306:3306
