version: '3'

services:
  https-portal:
    image: steveltn/https-portal
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DOMAINS: "localhost -> http://nginx:80"
      STAGE: "local"
      CLIENT_MAX_BODY_SIZE: 20M
    volumes:
      - ./docker/https-portal:/var/lib/https-portal

  db:
    image: mariadb:10.3.28-focal
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/conf:/etc/mysql/conf.d
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  php:
    depends_on:
      - db
    image: wordpress:php7.4-fpm
    # ports:
    #   - 8000:80
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  nginx:
    image: nginx
    # ports:
    #   - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # in local mailhog
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
volumes:
    db_data: